name: IPO Scanner

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5"   # 9:15â€“15:30 IST (convert: IST-5:30=UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------------------
      # GitHub Cache Restore
      # ---------------------------
      - name: Restore IPO history cache
        uses: actions/cache@v4
        with:
          path: ipo_history.pkl
          key: ipo-history-cache

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests

      - name: Run IPO Scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python ipo_scanner.py

      # ---------------------------
      # GitHub Cache Save
      # ---------------------------
      - name: Save IPO history cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ipo_history.pkl
          key: ipo-history-cache
