name: IPO Scanner

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5"   # runs every 15 min between 9:15â€“15:30 IST (UTC converted)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------------------
      # Restore Cache
      # ---------------------------
      - name: Restore IPO Cache
        uses: actions/cache@v4
        with:
          path: ipo_cache.pkl         # UPDATED FILE NAME
          key: ipo-cache-file         # cache key name

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests

      - name: Run IPO Scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python ipo_scanner.py

      # ---------------------------
      # Save Cache
      # ---------------------------
      - name: Save IPO Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ipo_cache.pkl         # UPDATED FILE NAME
          key: ipo-cache-file
